library(shiny)
library(mapview)
library(leaflet)
library(raster)
library(dplyr)
library(ggmap)
library(rgdal)
library(DT)
library(tidyr)
library(ggplot2)
library(rgeos)

gageInfo <- readRDS('data/gageInfo.RDS')
names(gageInfo) <- c('Gage Number','Description','LatDD','LongDD','HUC8','Drainage Area (sq mi)','name2','Web Address')
coordinates(gageInfo) <- ~LongDD+LatDD
proj4string(gageInfo) <- CRS("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0")                                 
